<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>10</LangVersion> 
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Lang.fs" />
    <Compile Include="State.fs" />
    <Compile Include="Monad.fs" />
    <Compile Include="Normalization.fs" />
    <Compile Include="RCInterpreter.fs" />
    <Compile Include="SourceInterpreter.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
